### ISSUE TITLE
Create menu class

### ISSUE THREAD

**Issue by RockyDesigne** [NextPP/sudoManager#10]
### Motivation

As a menu is central to any restaurant, implementing a menu class should be a priority. 
### Feature Description
The menu class will have one member variable, which will be a vector of items, representing all items on the menu.

It will have the following methods:

- `add_menu_item(item)`: adds a new MenuItem object to the menu_items list
- `remove_menu_item(item)`: removes a MenuItem object from the menu_items list
- `get_menu_item(item_name)`: returns the MenuItem object corresponding to the given item name
- `get_menu_item_price(item_name)`: returns the price of the MenuItem object corresponding to the given item name
- `print_menu()`: prints all the items on the menu

This is just a basic implementation of the menu class and more complexity can be added later.

**Comment by Chaitanya8135** [comment]
Hi ! Can I have this issue assigned to me ?!
