### ISSUE TITLE
Payment system

### ISSUE THREAD

**Issue by genciberisha** [NextPP/sudoManager#29]
### Descripe the feature and motivation

Payment will support:
- Cash
- Check
- Card

Requirements:
- \<<Payment\>> interface
- Bill class

### Payment interface requirements
- payment_id
- data of creation
- amount
- status: 
- init transaction method()
- 
### Bill class requirements
- id
- amount
- tip
- status: Paid/NotPaid
- method to generate the bill()

### Additional context

Feel free to get creative on what you think is fitter.
Implement that and we will discuss the PR if it is
a better idea :smile:

**Comment by RockyDesigne** [comment]
I'll be working on this one.
