### ISSUE TITLE
Create Item class

### ISSUE THREAD

**Issue by Jahrr** [NextPP/sudoManager#5]
### Description
As food items are the core object that this project will manage, it will be a good starting point.
The Item class should include member variables for

- Name of item
- Price
- Availability/Stock of item
- Potential sales or specials that an item can have, and whether they are in effect. 

This class should be as simple as possible, and it should be easy to interact with in other classes.

**Comment by Jahrr** [comment]
On second thought potential sales or specials can probably be handed by the menu instead of as presets

**Comment by jestoncolelewis** [comment]
Would adding in potential allergens be a good variable? That way servers can select/deselect allergens for customers. It gives a more direct way of informing the kitchen what to avoid.

**Comment by Jahrr** [comment]
That would be a good idea. If we wanted to go further we could create a separate ingrediants class contains the ingredients of every food item, along with possible allergens. Perhaps this is not necessary, but something to think about if we want to be as detailed as possible. Otherwise, adding allergens should be fairly straightforward, and can possibly be contained in an "additional information" string variable, or its own separate variable.

**Comment by genciberisha** [comment]
> ### Description
> 
> As food items are the core object that this project will manage, it will be a good starting point. The Item class should include member variables for
> 
>     * Name of item
> 
>     * Price
> 
>     * Availability/Stock of item
> 
>     * Potential sales or specials that an item can have, and whether they are in effect.
> 
> 
> This class should be as simple as possible, and it should be easy to interact with in other classes.
Take a look at the class diagram on the **Restaurant Management System** channel
